### ISSUE TITLE
Publish Dockerized postfix ports to host ports 25, 587, and 993

### ISSUE THREAD

**Issue by dav3r** [cisagov/pca-gophish-composition-packer#37]
# 💡 Summary #

Publish Dockerized postfix ports to instance host ports 25, 587, and 993.

## Motivation and context ##

We want this instance to be able to send and receive mail on official SMTP ports (25 and 587).
Also, we want to expose port 993 (IMAPS) so that the Dockerized dovecot IMAP server can be accessed by a local mail client.

## Implementation notes ##

The easiest way to do this is to add override the [default `postfix` published ports](https://github.com/cisagov/pca-gophish-composition#ports) by adding the following to the `services` section of [`docker-compose.production.yml`](https://github.com/cisagov/pca-gophish-composition-packer/blob/develop/src/docker-compose.production.yml):
```
postfix:
    ports:
      - target: "25"
        published: "25"
        protocol: tcp
        mode: host
      - target: "587"
        published: "587"
        protocol: tcp
        mode: host
      - target: "993"
        published: "993"
        protocol: tcp
        mode: host
```

## Acceptance criteria ##

- [ ] Executing `sudo netstat -ltnp` on the instance shows that ports 25, 587, and 993 are bound to a `docker-proxy` process
- [ ] Mail can be sent/received via ports 25 or 587
- [ ] The IMAPS server can be accessed via `localhost:993`
